export const ADD_LIST_ITEM = "ADD_LIST_ITEM";
export const REMOVE_LIST_ITEM = "REMOVE_LIST_ITEM";
export const TOGGLE_DONE = "TOGGLE_DONE";
export const SORT_DONE_ITEMS = "SORT_DONE_ITEMS";
export const SORT_NOT_DONE_ITEMS = "SORT_NOT_DONE_ITEMS";
export const SORT_ALL_ITEMS = "SORT_ALL_ITEMS";
export const SEARCH_ITEMS = "SEARCH_ITEMS";

